enum ImageUtils {
  POKEDEX,
  POKEBALL,
  POOKEBALLV2,
  ULTRABALL,
  THUNDER,
  LUCARIO,
  CHARMANDER,
  BULBASAUR,
  SQUIRTLE,
  CYNDAQUIL,
  TOTODILE,
  CHIKORITA,
  TORCHIC,
  MUDKIP,
  TREECKO,
  CHIMCHAR,
  PIPLUP,
  TURTWIG
}

const Map<ImageUtils, String> ImageUtilsSelection = {
  ImageUtils.POKEDEX: 'assets/pokedex.png',
  ImageUtils.POKEBALL: 'assets/Pokeball.png',
  ImageUtils.POOKEBALLV2: 'assets/Pokeballv2.png',
  ImageUtils.ULTRABALL: 'assets/ultraball.png',
  ImageUtils.THUNDER: 'assets/thunder.png',
  ImageUtils.LUCARIO: 'assets/Lucario.png',
  ImageUtils.CHARMANDER: 'assets/charmander.png',
  ImageUtils.BULBASAUR: 'assets/bulbasaur.png',
  ImageUtils.SQUIRTLE: 'assets/squirtle.png',
  ImageUtils.CHIMCHAR: 'assets/chimchar.png',
  ImageUtils.TOTODILE: 'assets/totodile.png',
  ImageUtils.CHIKORITA: 'assets/chikorita.png',
  ImageUtils.TORCHIC: 'assets/torchic.png',
  ImageUtils.MUDKIP: 'assets/mudkip.png',
  ImageUtils.TREECKO: 'assets/treecko.png',
  ImageUtils.PIPLUP: 'assets/piplup.png',
  ImageUtils.TURTWIG: 'assets/turtwig.png',
  ImageUtils.CYNDAQUIL: 'assets/cyndaquil.png',
};