// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl7l2TNV3r509qPP_mg0AjX7Uv6NQyqnc',
    appId: '1:720345402147:web:762805a20b7de253a3da96',
    messagingSenderId: '720345402147',
    projectId: 'pokedex-ultra-7e877',
    authDomain: 'pokedex-ultra-7e877.firebaseapp.com',
    storageBucket: 'pokedex-ultra-7e877.appspot.com',
    measurementId: 'G-EFP0B97DYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRdaGDSjR6o5pnRof8OQ5QKxYwzskHdjA',
    appId: '1:720345402147:android:a8d91cb74429f272a3da96',
    messagingSenderId: '720345402147',
    projectId: 'pokedex-ultra-7e877',
    storageBucket: 'pokedex-ultra-7e877.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnwC9R4Eb-vTXbgHxtGtsmCkWJV010sLU',
    appId: '1:720345402147:ios:4a2f801c8a6a3c9ba3da96',
    messagingSenderId: '720345402147',
    projectId: 'pokedex-ultra-7e877',
    storageBucket: 'pokedex-ultra-7e877.appspot.com',
    iosClientId: '720345402147-h0h7bugkapmnvaq9bn7irv9cdj9dh9il.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedexUltra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnwC9R4Eb-vTXbgHxtGtsmCkWJV010sLU',
    appId: '1:720345402147:ios:4a2f801c8a6a3c9ba3da96',
    messagingSenderId: '720345402147',
    projectId: 'pokedex-ultra-7e877',
    storageBucket: 'pokedex-ultra-7e877.appspot.com',
    iosClientId: '720345402147-h0h7bugkapmnvaq9bn7irv9cdj9dh9il.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedexUltra',
  );
}
